name: Zip and Rename Folders

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  zip_and_rename:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Ensure required tools are installed
      - name: Install zip utility
        run: sudo apt-get install -y zip

      # Find, zip, and rename folders
      - name: Zip and place .bgg files in proper folders
        run: |
          for folder in "Game Configs_TEST/Assets"/*; do
            if [ -d "$folder" ]; then
              folder_name=$(basename "$folder")
              zip -r "Game Configs_TEST/${folder_name}/${folder_name}.zip" "$folder"
              mv "Game Configs_TEST/${folder_name}/${folder_name}.zip" "Game Configs_TEST/${folder_name}/${folder_name}.bgg"
            fi
          done

      # Commit and push the .bgg files back to the repo
      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add Game\ Configs_TEST/*/*.bgg
          git commit -m "Add .bgg files for game Configs_TEST"
          git push
